
	LOAD DATA INFILE '/tmp/course_attributes1.csv' 
	INTO TABLE course_attributes FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_attributes_sections1.csv' 
	INTO TABLE course_attributes_sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_numberings1.csv' 
	INTO TABLE course_numberings FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/courses1.csv' 
	INTO TABLE courses FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/instructors1.csv' 
	INTO TABLE instructors FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/instructors_sections1.csv' 
	INTO TABLE instructors_sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/prerequisite_relations1.csv' 
	INTO TABLE prerequisite_relations FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/reviews1.csv' 
	INTO TABLE reviews FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/sections1.csv' 
	INTO TABLE sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/sessions1.csv' 
	INTO TABLE sessions FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/subjects1.csv' 
	INTO TABLE subjects FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/time_periods1.csv' 
	INTO TABLE time_periods FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/time_slots1.csv' 
	INTO TABLE time_slots FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/users1.csv' 
	INTO TABLE users FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_attributes1.csv' 
	INTO TABLE course_attributes FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_attributes_sections1.csv' 
	INTO TABLE course_attributes_sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_numberings1.csv' 
	INTO TABLE course_numberings FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/courses1.csv' 
	INTO TABLE courses FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/instructors1.csv' 
	INTO TABLE instructors FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/instructors_sections1.csv' 
	INTO TABLE instructors_sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/prerequisite_relations1.csv' 
	INTO TABLE prerequisite_relations FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/reviews1.csv' 
	INTO TABLE reviews FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/sections1.csv' 
	INTO TABLE sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/sessions1.csv' 
	INTO TABLE sessions FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/subjects1.csv' 
	INTO TABLE subjects FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/time_periods1.csv' 
	INTO TABLE time_periods FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/time_slots1.csv' 
	INTO TABLE time_slots FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/users1.csv' 
	INTO TABLE users FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_attributes1.csv' 
	INTO TABLE course_attributes FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_attributes_sections1.csv' 
	INTO TABLE course_attributes_sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_numberings1.csv' 
	INTO TABLE course_numberings FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/courses1.csv' 
	INTO TABLE courses FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/instructors1.csv' 
	INTO TABLE instructors FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/instructors_sections1.csv' 
	INTO TABLE instructors_sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/prerequisite_relations1.csv' 
	INTO TABLE prerequisite_relations FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/reviews1.csv' 
	INTO TABLE reviews FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/sections1.csv' 
	INTO TABLE sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/sessions1.csv' 
	INTO TABLE sessions FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/subjects1.csv' 
	INTO TABLE subjects FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/time_periods1.csv' 
	INTO TABLE time_periods FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/time_slots1.csv' 
	INTO TABLE time_slots FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/users1.csv' 
	INTO TABLE users FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_attributes2.csv' 
	INTO TABLE course_attributes FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_attributes_sections2.csv' 
	INTO TABLE course_attributes_sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/course_numberings2.csv' 
	INTO TABLE course_numberings FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/courses2.csv' 
	INTO TABLE courses FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/instructors2.csv' 
	INTO TABLE instructors FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/instructors_sections2.csv' 
	INTO TABLE instructors_sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/prerequisite_relations2.csv' 
	INTO TABLE prerequisite_relations FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/reviews2.csv' 
	INTO TABLE reviews FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/sections2.csv' 
	INTO TABLE sections FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/sessions2.csv' 
	INTO TABLE sessions FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/subjects2.csv' 
	INTO TABLE subjects FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/time_periods2.csv' 
	INTO TABLE time_periods FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/time_slots2.csv' 
	INTO TABLE time_slots FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	
	LOAD DATA INFILE '/tmp/users2.csv' 
	INTO TABLE users FIELDS TERMINATED BY ',' 
	OPTIONALLY ENCLOSED BY '"' ESCAPED BY '\\' 
	LINES TERMINATED BY '\n';
	